In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt, matplotlib.font_manager as fm
from datetime import datetime
import seaborn
%matplotlib inline

In [2]:
fitbit_sleep_intrad = pd.read_csv('../data/fitbit_sleep_intrad.csv', encoding='utf-8')
fitbit_sleep_intrad.drop(['Unnamed: 0'], axis=1, inplace=True)
fitbit_sleep_intrad

                        time  level  seconds
0    2023-10-22T22:52:30.000   wake      270
1    2023-10-22T22:57:00.000  light     3120
2    2023-10-22T23:49:00.000   deep      930
3    2023-10-23T00:04:30.000  light      570
4    2023-10-23T00:14:00.000    rem      450
..                       ...    ...      ...
140  2023-10-30T06:31:30.000  light      180
141  2023-10-30T06:34:30.000   wake      270
142  2023-10-30T06:39:00.000  light     1200
143  2023-10-30T06:59:00.000   wake      210
144  2023-10-30T07:02:30.000   deep       60

[145 rows x 3 columns]