In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt, matplotlib.font_manager as fm
from datetime import datetime
import seaborn
%matplotlib inline

In [2]:
fitbit_day = pd.read_csv('../data/fitbit_day.csv', encoding='utf-8')
fitbit_day.drop(['Unnamed: 0'], axis=1, inplace=True)
fitbit_day

,date,temp,activityCalories,br_deepSleepSummary,br_remSleepSummary,br_fullSleepSummary,br_lightSleepSummary
0,2023-10-22,NaN,31,NaN,NaN,NaN,NaN
1,2023-10-23,NaN,854,16.0,17.0,16.0,15.4
2,2023-10-24,NaN,592,15.8,16.6,15.8,15.8
3,2023-10-25,-0.0,456,16.0,16.2,16.0,15.8
4,2023-10-26,-0.3,1292,16.2,15.8,16.2,15.6
5,2023-10-27,2.1,2222,-1.0,-1.0,0.0,-1.0
6,2023-10-28,0.5,4146,18.6,-1.0,18.6,18.4
7,2023-10-29,0.8,2679,18.0,17.2,18.0,17.4
8,2023-10-30,0.1,213,17.4,17.6,17.4,16.8